[package]
name = "stm32f103-bluepill"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "stm32f103-bluepill"
test = false
bench = false

[dependencies]
kernel = { path = "../../kernel", default-features = false }
arch = { path = "../../arch", default-features = false }
bsp = { path = "../../bsp", default-features = false }

[features]
default = []
async_rt = ["kernel/async_rt", "arch/async_rt"]
builtin_shell = ["kernel/builtin_shell"]
st_hal_bridge = []