[workspace]
members = [
	"app",
	"arch",
	"bootloader",
	"drivers/cmsdk_uart",
	"drivers/lan9118",
	"drivers/ns16550a",
	"drivers/stm32l4x5_usart",
	"drivers/virtio_blk",
	"drivers/virtio_common",
	"drivers/virtio_gpu",
	"drivers/virtio_rng",
	"kernel",
	"platform/ionsoc-verilator",
	"platform/qemu-an521",
	"platform/qemu-stm32l475",
	"platform/qemu-virt-riscv",
	"xtask",
]

default-members = ["app", "arch", "kernel"]

resolver = "3"
