[workspace]
members = [
    "app",
    "arch",
    "bootloader",
    "bsp",
    "drivers/cmsdk_uart",
    "drivers/lan9118",
    "drivers/ns16550a",
    "drivers/virtio_blk",
    "drivers/virtio_common",
    "drivers/virtio_gpu",
    "drivers/virtio_rng",
    "kernel",
    "platform/ionsoc-verilator",
    "platform/qemu-an521",
    "platform/riscv-generic",
    "platform/stm32f103-bluepill",
    "xtask",
]

default-members = ["app", "arch", "kernel"]

resolver = "3"
