[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
kernel = { path = "../kernel", default-features = false }

[features]
default = ["builtin_shell"]
async_rt = ["kernel/async_rt"]
builtin_shell = ["kernel/builtin_shell"]
mcu_profile = ["kernel/mcu_profile"]
