[package]
name = "an521"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "an521"
test = false
bench = false


[dependencies]
kernel = { path = "../../kernel", default-features = false }
arch = { path = "../../arch", default-features = false }
app = { path = "../../app", default-features = false }
cmsdk_uart = { path = "../../drivers/cmsdk_uart", optional = true }
lan9118 ={ path = "../../drivers/lan9118", optional = true }

[features]
default = ["builtin_shell"]
async_rt = ["app/async_rt", "arch/async_rt"]
builtin_shell = ["app/builtin_shell"]
driver_cmsdk_uart = ["dep:cmsdk_uart"]
driver_lan9118 = ["dep:lan9118"]
